Parte addestramento della svm

In [0]:
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
import numpy as np
import scipy
from scipy import optimize
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report
from sklearn.svm import SVC

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [3]:
#da cambiare con nuova destinazione su drive Davide
%cd "/content/drive/My Drive"
filein = "vettori.csv"

df = np.genfromtxt(filein, delimiter=',', skip_header=1, filling_values=-999, dtype='float', usecols=[0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19])
X = df[:,0:18]
Y = df[:,19]



/content/drive/My Drive


In [4]:
#divido il dataset in training e test set
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.3,random_state=109) # 70% training and 30% test

print(X_train)
print(X_test)
print(y_train)
print(y_test)

[[0. 2. 0. ... 0. 0. 0.]
 [0. 2. 0. ... 0. 0. 0.]
 [2. 2. 0. ... 0. 0. 0.]
 ...
 [1. 2. 0. ... 0. 0. 0.]
 [0. 2. 0. ... 0. 0. 0.]
 [0. 2. 1. ... 0. 0. 0.]]
[[0. 2. 1. ... 0. 0. 0.]
 [1. 2. 0. ... 0. 0. 0.]
 [6. 2. 1. ... 0. 0. 0.]
 ...
 [4. 2. 1. ... 0. 0. 0.]
 [4. 2. 1. ... 0. 0. 0.]
 [1. 2. 0. ... 0. 0. 0.]]
[0. 1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0. 1. 1. 1. 1. 1. 1. 1. 1. 0. 1. 0. 1.
 1. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 1. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 1. 0. 1. 1. 1. 0. 0. 0. 1. 0. 1. 0. 1.
 0. 0. 0. 1. 0. 1. 1. 0. 0. 1. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 1. 1. 0. 1.
 1. 0. 1. 1. 1. 1. 0. 0. 1. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 1. 0. 0.
 1. 0. 1. 1. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 0. 0. 1. 1. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1.
 1. 0. 0. 0. 0. 1. 1. 1. 1. 0. 0. 0. 1. 1. 1. 1. 1. 0. 0. 1. 1. 0. 1. 0.
 1. 0. 1. 0. 0. 1. 1. 1. 1. 0. 0. 1.]


In [5]:
tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-1, 1e-6], 'C': [1, 10, 100, 1000]},
                    {'kernel': ['linear'], 'C': [1, 10, 100, 1000]},
                    {'kernel': ['poly'], 'gamma': [1e-1, 1e-6], 'C': [1, 10, 100, 1000]},
                    {'kernel': ['sigmoid'], 'gamma': [1e-1, 1e-6], 'C': [1, 10, 100, 1000]}]

scores = ['precision', 'recall']

for score in scores:
    print("# Tuning hyper-parameters for %s" % score)
    print()

    clf = GridSearchCV(
        SVC(), tuned_parameters, scoring='%s_macro' % score
    )
    clf.fit(X_train, y_train)

    print("Best parameters set found on development set:")
    print()
    print(clf.best_params_)
    print()
    print("Grid scores on development set:")
    print()
    means = clf.cv_results_['mean_test_score']
    stds = clf.cv_results_['std_test_score']
    for mean, std, params in zip(means, stds, clf.cv_results_['params']):
        print("%0.3f (+/-%0.03f) for %r"
              % (mean, std * 2, params))
    print()

    print("Detailed classification report:")
    print()
    print("The model is trained on the full development set.")
    print("The scores are computed on the full evaluation set.")
    print()
    y_true, y_pred = y_test, clf.predict(X_test)
    print(classification_report(y_true, y_pred))
    print()
    print()
    print(clf.best_params_.get('C'))

# Tuning hyper-parameters for precision



/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Pr

Best parameters set found on development set:

{'C': 1, 'gamma': 0.1, 'kernel': 'poly'}

Grid scores on development set:

0.861 (+/-0.056) for {'C': 1, 'gamma': 0.1, 'kernel': 'rbf'}
0.356 (+/-0.424) for {'C': 1, 'gamma': 1e-06, 'kernel': 'rbf'}
0.864 (+/-0.055) for {'C': 10, 'gamma': 0.1, 'kernel': 'rbf'}
0.356 (+/-0.424) for {'C': 10, 'gamma': 1e-06, 'kernel': 'rbf'}
0.845 (+/-0.077) for {'C': 100, 'gamma': 0.1, 'kernel': 'rbf'}
0.356 (+/-0.424) for {'C': 100, 'gamma': 1e-06, 'kernel': 'rbf'}
0.812 (+/-0.135) for {'C': 1000, 'gamma': 0.1, 'kernel': 'rbf'}
0.356 (+/-0.424) for {'C': 1000, 'gamma': 1e-06, 'kernel': 'rbf'}
0.854 (+/-0.082) for {'C': 1, 'kernel': 'linear'}
0.864 (+/-0.055) for {'C': 10, 'kernel': 'linear'}
0.853 (+/-0.066) for {'C': 100, 'kernel': 'linear'}
0.850 (+/-0.068) for {'C': 1000, 'kernel': 'linear'}
0.864 (+/-0.057) for {'C': 1, 'gamma': 0.1, 'kernel': 'poly'}
0.354 (+/-0.415) for {'C': 1, 'gamma': 1e-06, 'kernel': 'poly'}
0.854 (+/-0.082) for {'C': 10, 'gamma'

In [0]:
#SVM kernel lineare
clf_lineare = svm.SVC(kernel='linear')
clf_lineare.fit(X_train, y_train)
y_pred_lineare = clf_lineare.predict(X_test)

#SVM kernel rbf
clf_rbf = svm.SVC(kernel='rbf')
clf_rbf.fit(X_train, y_train)
y_pred_rbf = clf_rbf.predict(X_test)

#SVM kernel rbf auto
clf_rbf_auto = svm.SVC(kernel='rbf', gamma='auto')
clf_rbf_auto.fit(X_train, y_train)
y_pred_rbf_auto = clf_rbf_auto.predict(X_test)

#SVM kernel poly
clf_poly = svm.SVC(kernel='poly')
clf_poly.fit(X_train, y_train)
y_pred_poly = clf_poly.predict(X_test)

#SVM kernel poly auto
clf_poly_auto = svm.SVC(kernel='poly', gamma='auto')
clf_poly_auto.fit(X_train, y_train)
y_pred_poly_auto = clf_poly_auto.predict(X_test)

#SVM kernel sigmoid
clf_sigmoid = svm.SVC(kernel='sigmoid')
clf_sigmoid.fit(X_train, y_train)
y_pred_sigmoid = clf_sigmoid.predict(X_test)

#SVM kernel sigmoid auto
clf_sigmoid_auto = svm.SVC(kernel='sigmoid', gamma='auto')
clf_sigmoid_auto.fit(X_train, y_train)
y_pred_sigmoid_auto = clf_sigmoid_auto.predict(X_test)


#con grid_search
C_use = clf.best_params_.get('C')
gamma_use = clf.best_params_.get('gamma')
kernel_use = clf.best_params_.get('kernel')

clf_grid_search=svm.SVC(C = C_use, kernel = kernel_use, gamma = gamma_use)
clf_grid_search.fit(X_train, y_train)
y_pred_grid_search = clf_grid_search.predict(X_test)

In [7]:
#Accuracy, Precision, Recall per SVM con kernel lineare
print("Accuracy, Precision, Recall per SVM con kernel lineare\n")
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_lineare))
print("Precision:",metrics.precision_score(y_test, y_pred_lineare))
print("Recall:",metrics.recall_score(y_test, y_pred_lineare), "\n\n")

#Accuracy, Precision, Recall per SVM con kernel rbf
print("Accuracy, Precision, Recall per SVM con kernel rbf\n")
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_rbf))
print("Precision:",metrics.precision_score(y_test, y_pred_rbf))
print("Recall:",metrics.recall_score(y_test, y_pred_rbf), "\n\n")

#Accuracy, Precision, Recall per SVM con kernel rbf auto
print("Accuracy, Precision, Recall per SVM con kernel rbf auto\n")
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_rbf_auto))
print("Precision:",metrics.precision_score(y_test, y_pred_rbf_auto))
print("Recall:",metrics.recall_score(y_test, y_pred_rbf_auto), "\n\n")

#Accuracy, Precision, Recall per SVM con kernel poly
print("Accuracy, Precision, Recall per SVM con kernel poly \n")
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_poly))
print("Precision:",metrics.precision_score(y_test, y_pred_poly))
print("Recall:",metrics.recall_score(y_test, y_pred_poly), "\n\n")

#Accuracy, Precision, Recall per SVM con kernel poly auto
print("Accuracy, Precision, Recall per SVM con kernel poly auto \n")
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_poly_auto))
print("Precision:",metrics.precision_score(y_test, y_pred_poly_auto))
print("Recall:",metrics.recall_score(y_test, y_pred_poly_auto), "\n\n")

#Accuracy, Precision, Recall per SVM con kernel sigmoid
print("Accuracy, Precision, Recall per SVM con kernel sigmoid\n")
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_sigmoid))
print("Precision:",metrics.precision_score(y_test, y_pred_sigmoid))
print("Recall:",metrics.recall_score(y_test, y_pred_sigmoid), "\n\n")

#Accuracy, Precision, Recall per SVM con kernel sigmoid auto
print("Accuracy, Precision, Recall per SVM con kernel sigmoid\n")
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_sigmoid_auto))
print("Precision:",metrics.precision_score(y_test, y_pred_sigmoid_auto))
print("Recall:",metrics.recall_score(y_test, y_pred_sigmoid_auto), "\n\n")

print("Accuracy, Precision, Recall per SVM con utilizzo grid search\n\n")
print("Accuracy:",metrics.accuracy_score(y_test, y_pred_grid_search))
print("Precision:",metrics.precision_score(y_test, y_pred_grid_search))
print("Recall:",metrics.recall_score(y_test, y_pred_grid_search), "\n\n")

Accuracy, Precision, Recall per SVM con kernel lineare

Accuracy: 0.8
Precision: 0.78125
Recall: 0.8333333333333334 


Accuracy, Precision, Recall per SVM con kernel rbf

Accuracy: 0.8
Precision: 0.78125
Recall: 0.8333333333333334 


Accuracy, Precision, Recall per SVM con kernel rbf auto

Accuracy: 0.8166666666666667
Precision: 0.7878787878787878
Recall: 0.8666666666666667 


Accuracy, Precision, Recall per SVM con kernel poly 

Accuracy: 0.8
Precision: 0.78125
Recall: 0.8333333333333334 


Accuracy, Precision, Recall per SVM con kernel poly auto 

Accuracy: 0.7
Precision: 0.625
Recall: 1.0 


Accuracy, Precision, Recall per SVM con kernel sigmoid

Accuracy: 0.6833333333333333
Precision: 0.6774193548387096
Recall: 0.7 


Accuracy, Precision, Recall per SVM con kernel sigmoid

Accuracy: 0.8
Precision: 0.725
Recall: 0.9666666666666667 


Accuracy, Precision, Recall per SVM con utilizzo grid search


Accuracy: 0.8
Precision: 0.78125
Recall: 0.8333333333333334 




In [0]:
#esportazione della SVM addestrata
import pickle

filename = 'finalized_model.sav'
pickle.dump(clf_grid_search, open(filename, 'wb'))